### ISSUE TITLE
Structure / namespacing

### ISSUE THREAD

**Issue by maxkfranz** [jri/cytoscape-edge-connections#1]
It would be good if this extension handled namespacing a bit better.  It's best if an extension only sets data under `ele.scratch('myExtensionName')` and if it only exposes `ele.myExtensionName()` and `cy.myExtensionName()`.

For example:

```js
const ec = cy.edgeConnections();

ec.addEdge(edge);
ec.addEdges(edges);
ec.getAuxNode(edge);
ec.isAuxNode(node);
ec.getEdgeId(auxNode);

// within the above, only data is set within `ele.scratch('edgeConnections')`
```

It's best to follow this practice, because eventually another extension, the core lib, or an app's code will clobber the function or data at non-namespaced keys.

**Comment by jri** [comment]
Thank you for the hints!
I'll improve the extension accordingly and release a new version soon.

**Comment by jri** [comment]
Version 0.3 of the extension is now released.
From README:
```
* Proper extension namespacing (thanks to @maxkfranz):
    * Initializer returns API object (don't clobber Cytoscape's core and collection API)
    * Internal: use a scratchpad to enrich edge data
```

**Comment by maxkfranz** [comment]
Perfect, thanks @jri!
