### ISSUE TITLE
Remove edge

### ISSUE THREAD

**Issue by Dassderdie** [jri/cytoscape-edge-connections#2]
If you remove an aux-node you get those console-errors:

```
cytoscape-edge-connections.min.js:1 Data inconsistency: aux node of edge Be {0: Be, length: 1, _private: {…}} not in graph, auxNodeId 8226739c-b017-4c62-829f-432b7d6e39d0 ...

cytoscape-edge-connections.min.js:1 Uncaught Error: data inconsistency: aux node of edge 500 not in graph ...
```

I want to clear the cytoscape graph. Therefore I just added `cy.filter('*').remove();` to the end of the demo:
https://plnkr.co/edit/23jg04nebyRRZ0HiX334?p=preview

Is there an intended way of doing this?

**Comment by jri** [comment]
The extension expects an aux node still to exist at the time its edge is removed.  
So you must remove the edges first:
```
cy.remove('edge')
cy.remove('node')
```

**Comment by Dassderdie** [comment]
Thx for the response :)

I tried to reproduce the errors I get in my application and this is the result:
  
https://plnkr.co/edit/23jg04nebyRRZ0HiX334?p=preview

It is possible to remove the edges the first time like this, but the second time it throws errors...

**Comment by jri** [comment]
Please provide another plnkr for me to reproduce your problem.  
Note that both plnkr's you've provided are the same.  
The 2nd does not add any new information for me to work with.

**Comment by Dassderdie** [comment]
Ops, sorry.
This should do the trick: https://plnkr.co/edit/P9XkCo0cRbyxwxTIICGj?p=preview

**Comment by jri** [comment]
The problem is you're initializing the edge-connections extension twice, that is in every `addElements()` call.

Do instantiation only once, then it works:
```
var cy = cytoscape(...)
var ec = cy.edgeConnections()

function addElements() {
  ec.addEdges(...)
}
```

**Comment by Dassderdie** [comment]
Yeah, that was the mistake...

Thank you very much for your help  👍

**Comment by jri** [comment]
You're welcome!
