### ISSUE TITLE
Demo page does not draw edges

### ISSUE THREAD

**Issue by Konard** [jri/cytoscape-edge-connections#4]
Could you update the demo page to use the latest version of the extension?

**Comment by jri** [comment]
I've checked the demo page and can't see any problem. The edge-connected edges appear properly:

![image](https://user-images.githubusercontent.com/120337/65066100-0425b000-d984-11e9-8500-e4c4f8515e93.png)

Also the demo page uses the latest version. When you look at its HTML source you see that the unpkg link contains no version number:
```html
<script src="https://unpkg.com/cytoscape-edge-connections"></script>
```
That is unpkg delivers the latest version. Paste that URL into the address bar and you'll see unpkg.com redirects to @0.4.1, which is the latest version:

![image](https://user-images.githubusercontent.com/120337/65066871-89f62b00-d985-11e9-96c5-716ee0cc18a2.png)

I can also acknowledge that the dist file (`cytoscape-edge-connections.min.js`) has been properly build before publishing the package.

So, what is your actual problem? What makes you think the demo page has not the latest version?

Have you tried clearing the browser cache? Try also restarting the browser, and try different browsers. Also check for messages appearing in the browser console.

**Comment by Konard** [comment]
Strange, after the update of Google Chrome everything looks ok.
